<script setup lang="ts">
import { computed, ref } from 'vue';
import PageHeading from '../components/PageHeading.vue';
import { playtestItems, summarizePlaytest, type TestOutcome } from '../features/playtest.ts';
import { downloadJson } from '../storage/backup.ts';
const device = ref(''), system = ref(''), group = ref('01'), age = ref('小学一年级'), orientation = ref('横屏'), assistance = ref(''), firstCreate = ref(''), firstCatch = ref(''), favourite = ref(''), notes = ref(''), exported = ref(false);
const rows = ref(playtestItems.map(item => ({ id: item.id, outcome: 'unmeasured' as TestOutcome, note: '' })));
const summary = computed(() => summarizePlaytest(rows.value));
const begun = new Date().toISOString();
function exportRecord() { downloadJson({ format: 'fish-family-playtest-v1', version: 1, begun, exportedAt: new Date().toISOString(), device: device.value, system: system.value, userAgent: navigator.userAgent, viewport: { width: innerWidth, height: innerHeight, dpr: devicePixelRatio }, group: group.value, age: age.value, orientation: orientation.value, assistance: assistance.value, firstCreationMinutes: firstCreate.value, firstCatchMinutes: firstCatch.value, favourites: favourite.value, notes: notes.value, rows: rows.value, summary: summary.value, evidenceType: 'manually-entered-observations', physicalDeviceVerified: false, formalReleaseApproved: false }, `我的海洋-家庭试玩-${group.value.replace(/[^A-Za-z0-9_-]/g, '') || '01'}.json`); exported.value = true; }
</script>
<template><PageHeading eyebrow="一起试试 / FAMILY PLAYTEST" title="看看哪里好玩，哪里卡住。" description="先自由玩一会儿，再记录。空白和未测都保留；不需要孩子姓名、照片或每天来玩。"/><section class="playtest-sheet"><nav><RouterLink to="/create" class="button button--muted" target="_blank">🖌️ 造鱼</RouterLink><RouterLink to="/ocean" class="button button--muted" target="_blank">🌊 海洋</RouterLink><RouterLink to="/journal" class="button button--muted" target="_blank">🐟 图鉴</RouterLink></nav><h2>设备与这次试玩</h2><div class="test-fields"><label>设备型号<input v-model="device" maxlength="100" placeholder="iPad 9"></label><label>系统和浏览器版本<input v-model="system" maxlength="100" placeholder="iPadOS · Safari"></label><label>组号<input v-model="group" maxlength="20"></label><label>年龄段<input v-model="age" maxlength="30"></label><label>屏幕方向<select v-model="orientation"><option>横屏</option><option>竖屏</option><option>都测了</option></select></label><label>帮助、挑战与成人接手<input v-model="assistance" maxlength="200" placeholder="例如一起玩；提竿时帮了一次"></label><label>第一条作品用时（分钟）<input v-model="firstCreate" type="number" min="0" max="180" step="0.5"></label><label>首次钓到用时（分钟）<input v-model="firstCatch" type="number" min="0" max="180" step="0.5"></label></div><h2>实际操作记录</h2><article v-for="(item, i) in playtestItems" :key="item.id"><div><h3>{{ item.title }}</h3><p>{{ item.hint }}</p></div><label><span class="visually-hidden">{{ item.title }}结论</span><select v-model="rows[i]!.outcome" :aria-label="`${item.title}结论`"><option value="unmeasured">未测</option><option value="passed">通过</option><option value="failed">有问题</option></select></label><label class="test-note"><span class="visually-hidden">{{ item.title }}现象</span><textarea :aria-label="`${item.title}现象`" v-model="rows[i]!.note" maxlength="1200" placeholder="具体按钮、阶段、现象和复测结果"/></label></article><label class="wide-field">喜欢什么鱼、什么动作？<textarea v-model="favourite" maxlength="2000"/></label><label class="wide-field">孩子的话、卡点和下一次修改<textarea v-model="notes" maxlength="4000"/></label><div class="test-export"><p>已填通过 {{ summary.passed }} · 有问题 {{ summary.failed }} · 未测 {{ summary.unmeasured }}</p><button class="button" @click="exportRecord">下载这次试玩记录</button></div><p v-if="exported" role="status">记录文件已生成。保留失败项，修好以后另存一次复测记录。</p><p class="test-limit">表单在这次打开期间保留，刷新前请导出。填写设备型号不等于已验证硬件；帧预算需分别从钓场、平面海洋和立体海洋导出。本表不会自动批准正式发布。</p></section></template>
<style scoped>.playtest-sheet{max-width:1050px;margin:auto;padding:24px;background:#fbfcf3;border:1px solid #d0dfcf;border-radius:24px;color:#315b4d}nav{display:flex;flex-wrap:wrap;gap:8px}h2{font-size:22px;margin:24px 0 16px}.test-fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}label{font-size:13px;line-height:1.8}input,select,textarea{min-height:44px;padding:10px;border:1px solid #c5d9c9;border-radius:11px;background:white;color:#315b4d;font:inherit;font-size:14px;max-width:100%}.test-fields input,.test-fields select{display:block;width:100%;margin-top:6px}article{display:grid;grid-template-columns:minmax(0,1fr) 110px;gap:8px 18px;padding:16px 0;border-top:1px solid #d9e5d6}h3{font-size:16px}p{font-size:13px;line-height:1.8}article p{margin-top:5px;color:#607c68}.test-note{grid-column:1/-1}textarea{width:100%;min-height:75px;resize:vertical}.wide-field{display:block;margin:18px 0}.test-export{display:flex;align-items:center;justify-content:space-between;gap:15px;margin-top:20px}.test-limit{margin-top:18px;color:#6e826c}@media(max-width:550px){.playtest-sheet{padding:14px}.test-fields{grid-template-columns:1fr}article{gap:8px;grid-template-columns:minmax(0,1fr) 100px}.test-export{flex-direction:column;align-items:stretch}}</style>
