<script setup lang="ts">
import { defineAsyncComponent, nextTick, onBeforeUnmount, ref } from 'vue';
import OceanTank, { type FishTextures, type OceanActor } from './OceanTank.vue';
const CreativeOcean3d = defineAsyncComponent(() => import('./CreativeOcean3d.vue'));
import { usePreferences } from '../features/preferences.ts';
const props = defineProps<{ fish: OceanActor[]; textures: Map<string, FishTextures>; disabled?: boolean }>();
const emit = defineEmits<{ change: [open: boolean] }>();
const dialog = ref<HTMLDialogElement>(), button = ref<HTMLButtonElement>(), open = ref(false), paused = ref(false), volume = ref(false), message = ref('');
const prefs = usePreferences(); let alive = true;
function show() { if (props.disabled) return; open.value = true; paused.value = false; message.value = ''; emit('change', true); dialog.value?.showModal(); }
async function close() { if (!open.value) return; if (document.fullscreenElement === dialog.value) await document.exitFullscreen().catch(() => undefined); open.value = false; emit('change', false); await nextTick(); if (alive) button.value?.focus({ preventScroll: true }); }
async function full() { try { await dialog.value?.requestFullscreen(); } catch { message.value = '已铺满浏览器画面；这个浏览器暂时不支持隐藏系统工具栏。'; } }
onBeforeUnmount(() => { alive = false; });
</script>
<template><div class="local-ocean-display"><button ref="button" class="button button--muted" :disabled="disabled" @click="show">📺 全屏看海洋</button><dialog ref="dialog" aria-labelledby="local-display-title" @close="close" @cancel.prevent="dialog?.close()"><template v-if="open"><header><h2 id="local-display-title">我的海洋 · {{ fish.length }} 条小伙伴</h2><div><button :aria-pressed="paused" @click="paused = !paused">{{ paused ? '▶ 继续游' : '⏸ 停一停' }}</button><button :aria-pressed="volume" @click="volume = !volume">{{ volume ? '🌊 看画出来的海' : '🌀 看立体海' }}</button><button @click="full">⛶ 铺满屏幕</button><button autofocus @click="dialog?.close()">✕ 返回</button></div></header><CreativeOcean3d v-if="volume" :fish="fish" :textures="textures" :paused="paused" @fallback="volume = false; message = '立体画面暂时不可用，已回到原来的海洋。'"/><OceanTank v-else :fish="fish" :textures="textures" :selected-id="null" :highlight-id="null" :reduced-motion="prefs.reducedMotion.value" :paused="paused"/><p v-if="!fish.length" class="local-display-empty">还没有小伙伴在海里，回去放入一条作品吧。</p><p class="local-display-note" role="status">{{ message || '只在本机展示，不发送作品到其他设备。' }}</p></template></dialog></div></template>
<style scoped>.local-ocean-display{display:inline-flex}dialog{width:100vw;height:100dvh;max-width:none;max-height:none;margin:0;padding:0;border:0;background:#287c89;color:#f2f9e6;overflow:hidden}dialog::backdrop{background:#174455}header{position:absolute;z-index:5;top:12px;left:16px;right:16px;display:flex;align-items:center;justify-content:space-between;gap:12px;pointer-events:none}h2{font-size:18px;text-shadow:0 2px 6px #175367}header>div{display:flex;gap:6px;flex-wrap:wrap;pointer-events:auto}header button{min-height:44px;min-width:44px;padding:9px 12px;border:1px solid #d9e5d3;border-radius:13px;background:#fff8eade;color:#345c4e;font-size:12px;cursor:pointer}dialog :deep(.ocean-tank),dialog :deep(.volume-ocean-stage){height:100dvh!important;max-height:none!important;border-radius:0!important;margin:0!important}dialog :deep(.ocean-playbar),dialog :deep(.ocean-measurement),dialog :deep(.ocean-parent-tools),dialog :deep(.volume-ocean-tools),dialog :deep(.creative-ocean-3d>details),dialog :deep(.scene-label){display:none}.local-display-note{position:absolute;bottom:12px;left:16px;right:16px;font-size:12px;pointer-events:none;text-shadow:0 2px 6px #175367}.local-display-empty{position:absolute;top:45%;left:10%;right:10%;text-align:center;background:#174859b8;padding:16px;border-radius:18px}@media(max-width:550px){header{align-items:flex-start}h2{font-size:13px;max-width:30%}header>div{max-width:70%;justify-content:flex-end}header button{padding:8px;font-size:11px}}</style>
